data = open(r"C:\Users\HP\OneDrive\Desktop\Python Program\File Hadling\demo.txt","r")
line1 = data.readline()
print(line1)
line2 = data.readline()
print(line2)
content = data.read(3)
print(content)
print(type(content))
data.close()
